### PR TITLE
fix(core): wrap `setFiltersFn` with `useCallback`

### LINKED ISSUE #6385: [BUG] setFilters from useDataGrid causes infinite loop inside useEffects
### Describe the bug

I was trying to use the `setFilters` from the useDataGrid hook in a custom debounce function that are attached with a state. I have something very simple like:
```
useEffect(() => {
    setFilters(
      [
        {
          field: "id",
          value: debouncedSearchInput,
          operator: "eq",
        },
      ],
      "replace"
    );
  }, [debouncedSearchInput, search,  setFilters]);
```

The code above is causing a infinite loop. After investigate a bit I realised that inside the `useTable` hook the `setFiltersFn` are not wrapped in a `useCallback` and this causing changes in states changes the reference of the function and bc of that it's impossible pass the `setFilters` as a dependency.

The fix is quite easy, I can open a PR for fixing it.

### Steps To Reproduce

1. get the `setFilters` from `useDataGrid`
2. use it in a useEffect and pass setFilters as a dependency.
3. infinite loop

### Expected behavior

Use setFilters as a dependency should not cause infinite loop

### Packages

- @refinedev/core

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by hugorezende**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

Adding the `setFilters` as a dependency in the useEffect hook causes infinite loop since setFiltersFn are not wrapped in `useCallbacks`

## What is the new behavior?

No infinite loop

fixes #6385

### CODE REVIEW

File: packages/core/src/hooks/useTable/index.ts [hunk 1]
```diff
@@ -520,36 +520,49 @@ export function useTable<
...
-      unionFilters(preferredPermanentFilters, newFilters, prevFilters),
-    );
-  };
+  const setFiltersAsMerge = useCallback(
+    (newFilters: CrudFilter[]) => {
+      setFilters((prevFilters) =>
+        unionFilters(preferredPermanentFilters, newFilters, prevFilters),
+      );
+    },
+    [setFilters, unionFilters, preferredPermanentFilters],
```
Comment (aliemir) [inline packages/core/src/hooks/useTable/index.ts:529]: `setFilters` is a SetStateAction and `unionFilters` is an imported util, they don't need to be included in the dependency arrays.

Comment (aliemir) [reply packages/core/src/hooks/useTable/index.ts:529]: Also can you make a similar update in the `setSortWithUnion` function as well? 🙏

File: .changeset/spotty-jokes-swim.md [hunk 2]
```diff
@@ -0,0 +1,9 @@
+---
+"@refinedev/core": patch
+---
+
+fix: fix setFiltersFn #6385
```
Comment (aliemir) [inline .changeset/spotty-jokes-swim.md:5]:
```suggestion
fix(core): wrap `setFilters` and `setSorters` methods with `useCallback` to prevent looping re-renders
```

Having a bit more info in the first line will be great for the changelogs 😅

**Review by aliemir — CHANGES_REQUESTED** [review]
Hey @hugorezende thank you for the PR! I've made a small change request in the changeset and left two comments for the dependency arrays, can you check them and apply the necessary changes? 🙏 

Then, we can include this in our next release 🚀 🚀

File: packages/core/src/hooks/useTable/index.ts (hunk 1 above)
Comment (hugorezende) [reply packages/core/src/hooks/useTable/index.ts]: hey @aliemir, thanks for checking the PR. I'm just so used with the exhaustive rule i didn't realised it 😄  
Just fixed those and also added it on `setSortWithUnion` 
990f8e9

**Review by alicanerdurmaz — APPROVED** [review]
