### PR TITLE
fix(app-crm): search input should work sync with location

### LINKED ISSUE #5798: [BUG] Refreshing a page with Ant Design's useTable's search usage doesn't bring back the value
### Describe the bug

Hello,
When following the example from the official documentation [Ant Design's useTable's search](https://refine.dev/docs/ui-integrations/ant-design/hooks/use-table/#search), I found that when ` syncWithLocation: true`, the url's parameters are not in `searchFormProps.initialValues` and the `onSearch` hook is not triggered on the first render, but the parameters are brought in when requesting the API, is this a bug? If it is not an error, please let me know the solution.
Thanks, team

### Steps To Reproduce

1. Follow [Ant Design's useTable's search](https://refine.dev/docs/ui-integrations/ant-design/hooks/use-table/#search) to complete the example.
2. Enable `syncWithLocation: true`.
3. Unable to find url parameter in `searchFormProps.initialValues`.

### Expected behavior

Normal echoing of parameters from the url to the search form

### Packages

 - @renfinedev/antd@5.37.4

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alicanerdurmaz**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [ ] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

fixes #5798

https://github.com/refinedev/refine/assets/23058882/d033c7c7-b225-4ba8-a90c-f05fb7e947d0

### CODE REVIEW

File: examples/app-crm/src/routes/companies/list.tsx [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import { FC, PropsWithChildren, useState } from "react";
 
 import { List, useTable } from "@refinedev/antd";
-import { HttpError } from "@refinedev/core";
+import { HttpError, getDefaultFilter } from "@refinedev/core";
```
Comment (aliemir) [inline examples/app-crm/src/routes/companies/list.tsx:4]:
```suggestion
import { getDefaultFilter, HttpError } from "@refinedev/core";
```

**Review by aliemir — APPROVED** [review]
