### PR TITLE
fix(icon): changed profile icon as user icon in store

### LINKED ISSUE #2777: [BUG] Updating the my profile icon
### Describe the bug

The  Profile Icon looks so simple and the icon need to something that tells the user that its the profile icon and the current icon lacks that

### Steps To Reproduce

Go to "https://store.refine.dev/"
The top uppermost right corner

### Expected behavior

Need Enhancement

### Screenshot

_No response_

### Desktop

_No response_

### Mobile

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by s-vamshi**
Replaced avatar component with user icon component.

image

On hover: 
image

closes #2777 

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

### CODE REVIEW

File: examples/store/src/components/common/UserNav/UserNav.tsx [hunk 1]
```diff
@@ -6,7 +6,7 @@ import { LineItem } from "@medusajs/medusa";
 
 import { Avatar } from "@components/common";
```
Comment (sevkioruc) [inline examples/store/src/components/common/UserNav/UserNav.tsx:7]: If `Avatar` don't be used other place in this file, could you please remove it?

Comment (s-vamshi) [reply examples/store/src/components/common/UserNav/UserNav.tsx:7]: Should I remove whole file or only the import statement?

Comment (aliemir) [reply examples/store/src/components/common/UserNav/UserNav.tsx]: Thanks for pointing this out @sevkioruc  🙏

File: examples/store/src/components/icons/User.tsx [hunk 2]
```diff
@@ -1,14 +1,13 @@
...
-    size = "16",
     color = "currentColor",
     ...props
 }) => {
     return (
         <svg
-            width={size}
-            height={size}
+            width="22"
+            height="24"
```
Comment (aliemir) [inline examples/store/src/components/icons/User.tsx:10]: `<User/>` is also used in the profile page and this change might be an issue for it, can't we use `size` prop instead of declaring them statically? If `height=24` is for alignment maybe we can use `mt-px` or something like that?

Comment (s-vamshi) [reply examples/store/src/components/icons/User.tsx]: @aliemir I have added props for user icon component can you please check now?

**Comment by aliemir** [comment]
Thanks for the changes @s-vamshi!
