### PR TITLE
fix: support `getList` method pagination/without pagination for `@refinedev/nestjsx-crud` 

### LINKED ISSUE #4572: [BUG] TypeError: Cannot read properties of undefined (reading 'map')
### Describe the bug

When I use hook useSelect with @refinedev/nestjsx-crud I receive error: 
"TypeError: Cannot read properties of undefined (reading 'map')"

I found mistake in dataProvider in method getList. This method return object like

```
    return {
      data: data.data,
      total: data.total,
    };
```
For useList it's okay, but for useSelect need return 
```
    return {
      data: data,
      total: data.total,
    };
```

### Steps To Reproduce

1. yarn create refine-app 
image
2. open file /pages/blog-posts/create/index.tsx and replace code
```
import { GetServerSideProps } from 'next';
import { Create, useForm, useSelect } from '@refinedev/antd';
import { useList } from '@refinedev/core';
import { Form, Input, Select } from 'antd';
import { authProvider } from 'src/authProvider';

export default function BlogPostCreate() {
  const { formProps, saveButtonProps } = useForm<IPost>();
  const { data } = useList<IPost>({
    resource: 'categories',
  });

  const { selectProps: categorySelectProps } = useSelect<IPost>({
    resource: 'categories',
  });

  console.log(
    '🚀 ~ file: index.tsx:17 ~ BlogPostCreate ~ categorySelectProps:',
    categorySelectProps,
  );

  return (
    <Create saveButtonProps={saveButtonProps}>
      <Form {...formProps} layout="vertical">
        <Form.Item label="Title" name="title">
          <Input />
        </Form.Item>
        <Form.Item label="Status" name="status">
          <Select
            options={[
              {
                label: 'Published',
                value: 'published',
              },
              {
                label: 'Draft',
                value: 'draft',
              },
              {
                label: 'Rejected',
                value: 'rejected',
              },
            ]}
          />
        </Form.Item>
        <Form.Item label="Category" name={['category', 'id']}>
          {categorySelectProps && <Select {...categorySelectProps} />}
        </Form.Item>
      </Form>
    </Create>
  );
}

export const getServerSideProps: GetServerSideProps<{}> = async context => {
  const { authenticated, redirectTo } = await authProvider.check(context);

  if (!authenticated) {
    return {
      props: {},
      redirect: {
        destination: `${redirectTo}?to=${encodeURIComponent('/blog-posts')}`,
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};
```
3. run app and click on "Create" button on blog posts list

### Expected behavior

useSelect should be work

### Screenshot

image

### Desktop

_No response_

### Mobile

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by yildirayunlu**
Without the `limit` and `offset` parameters in the [`nestjsx/crud`](https://github.com/nestjsx/crud) library, the result is without paging. However, it was always expected to be paginated in the data provider. It now supports both situations.

### Test plan (required)

image

### Closing issues

closes #4572

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

### CODE REVIEW

**Review by aliemir — APPROVED** [review]

File: packages/nestjsx-crud/src/provider.ts [hunk 1]
```diff
@@ -26,9 +26,18 @@ export const dataProvider = (
...
 
+        // with pagination
+        if (data.data && data.total) {
+            return {
+                data: data.data,
+                total: data.total,
+            };
+        }
+
+        // without pagination
```
Comment (aliemir) [inline packages/nestjsx-crud/src/provider.ts:37]: Can we check for `Array.isArray(data)` here? Let's make sure we've received an array.

File: packages/nestjsx-crud/test/getList/index.spec.ts [hunk 2]
```diff
@@ -132,4 +132,20 @@ describe("getList", () => {
         expect(data[1]["title"]).toBe("Avon heuristic Washington");
         expect(total).toBe(2);
     });
+
+    it("correct response with out pagination", async () => {
+        const { data, total } = await JsonServer(
+            "https://api.nestjsx-crud.refine.dev",
```
Comment (BatuhanW) [inline packages/nestjsx-crud/test/getList/index.spec.ts:138]: Is this request mocked or is it making actual request to API? If so, let's mock the response, so test won't randomly fail if some data changes.

File: packages/nestjsx-crud/test/getList/index.spec.ts [hunk 3]
```diff
@@ -132,4 +132,20 @@ describe("getList", () => {
         expect(data[1]["title"]).toBe("Avon heuristic Washington");
         expect(total).toBe(2);
     });
+
+    it("correct response with out pagination", async () => {
```
Comment (BatuhanW) [inline packages/nestjsx-crud/test/getList/index.spec.ts:136]:
```suggestion
    it("correct response without pagination", async () => {
```

File: packages/nestjsx-crud/test/getList/index.mock.ts [hunk 4]
```diff
@@ -2458,3 +2458,572 @@ nock("https://api.nestjsx-crud.refine.dev:443", {
...
+                    {
+                        id: "ff780da9-2a1b-4030-8ecf-5cb9f520ec34",
+                        title: "brand",
+                        createdAt: "2021-06-21T11:13:33.006Z",
+                        updatedAt: "2021-06-21T11:13:33.006Z",
+                    },
+                    {
+                        id: "9f84d769-c026-44b0-a946-16dd94178a0f",
+                        title: "boliviano Mvdol",
+                        createdAt: "2021-06-21T11:13:33.016Z",
```
Comment (BatuhanW) [inline packages/nestjsx-crud/test/getList/index.mock.ts:2679]: Let's not unnnecessarily add huge data here. We aren't using them on tests. We can only keep the relevant data which we assert in the spec.

**Review by BatuhanW — APPROVED** [review]
