### PR TITLE
fix(antd): filtering dates on table does not work with syncWithLocation

### LINKED ISSUE #5933: Date range table filter in Ant Design is broken
### Describe the bug

Hi everyone, while trying to replicate the Ant Design Crm example I noticed that the date range filter doesn't work as it should: https://example.crm.refine.dev/administration/audit-log.

When filtering by the "Date & Time" column and subsequently reloading the page, the following error occurs:
```
invalid input syntax for type timestamp: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN"
Error (status code: INTERNAL_SERVER_ERROR)
```

Then if you try to filter the same column again, the application will crash.

Other types of filters work properly, so I think that there might be something wrong with the conversion of the date values from the url to CrudFilter objects or vice-versa.

Here's a video of the bug:

https://github.com/refinedev/refine/assets/49818192/fe591efd-d17c-46b5-b9ed-3197b8700270

### Steps To Reproduce

1. Visit: https://example.crm.refine.dev/administration/audit-log.
2. Filter the "Date & Time" column by a range of dates.
3. Reload the page and an error will be thrown.
4. Then try to filter by the "Date & Time" column again and the app will crash.

### Expected behavior

Upon reloading the page with the same URL, the "Date & Time" column should be filtered with valid dates, and the query should function correctly.

### Packages

- @refinedev/antd
- @refinedev/core

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alicanerdurmaz**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [x] Tests for the changes have been added
- [x] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

Filtering [`<Table />`](https://refine.dev/docs/ui-integrations/ant-design/hooks/use-table/) with [`<FilterDropdown />`](https://refine.dev/docs/ui-integrations/ant-design/components/filter-dropdown) and [`<DatePicker />`](https://ant.design/components/date-picker) doesn't work with `syncWithLocation`. #5933

## What is the new behavior?

Added [`rangePickerFilterMapper`](https://refine.dev/docs/ui-integrations/ant-design/components/filter-dropdown/#rangepickerfiltermapper) utility function to convert `selectedKeys` to satisfy both the Refine(data provider, syncWithLocation etc.) and [`<DatePicker.RangePicker />`](https://ant.design/components/date-picker).

fixes #5933

### CODE REVIEW

**Review by omeraplak — APPROVED** [review]

File: examples/app-crm/src/routes/administration/audit-log.tsx [hunk 1]
```diff
@@ -147,7 +148,12 @@ export const AuditLogPage = () => {
               />
             )}
             filterDropdown={(props) => (
-              <FilterDropdown {...props}>
+              <FilterDropdown
+                {...props}
+                mapValue={(selectedKeys, event) => {
+                  return rangePickerFilterMapper(selectedKeys, event);
+                }}
```
Comment (aliemir) [inline examples/app-crm/src/routes/administration/audit-log.tsx:155]:
```suggestion
                mapValue=rangePickerFilterMapper}
```

File: packages/antd/src/components/table/components/filterDropdown/index.tsx [hunk 2]
```diff
@@ -1,12 +1,17 @@
...
+type AntdFilterDropdownProps = React.ComponentProps<
+  Exclude<TableColumnProps<any>["filterDropdown"], ReactNode>
+>;
+
+export type MapValueEvent = "onChange" | "value";
+
 export type FilterDropdownProps = AntdFilterDropdownProps & {
-  mapValue?: (selectedKeys: React.Key[]) => any;
+  mapValue?: (selectedKeys: React.Key[], event: MapValueEvent) => any;
   children: ReactNode;
```
Comment (aliemir) [inline packages/antd/src/components/table/components/filterDropdown/index.tsx:15]:
```suggestion
  children: JSX.Element;
```

Can we also do this to enforce single child for `<FilterDropdown>`?

**Review by aliemir — CHANGES_REQUESTED** [review]
Left two small comments, other than these, we're good to go! 🚀

**Review by aliemir — APPROVED** [review]
