### PR TITLE
fix(inferencer): improve relational field inference

### LINKED ISSUE #5184: Inferencer + Supabase + foreign key: Objects are not valid as a React child
### Describe the bug

When I open my local refine project http://localhost:5173/members I get error

```
Error: Objects are not valid as a React child (found: object with keys {id, team_name}). If you meant to render a collection of children, use an array instead.
```

#### Details

Inferencer sends request:

`GET https://*****.supabase.co/rest/v1/teams?select=*&id=in.%281%29`

Result:

```
[{"id":1,"team_name":"Village of the Hidden Mist"}]
```

### Steps To Reproduce

Project: https://github.com/d9k/d9k-examples/tree/main/ts/supabase-refine

Supabase PostgreSql dump:
https://github.com/d9k/d9k-examples/blob/main/ts/supabase-demo/demo.sql

#### `<MembersList>` source:

https://github.com/d9k/d9k-examples/blob/main/ts/supabase-refine/src/pages/members/list.tsx

### Expected behavior

No error, visible datagrid.

### Screenshot

Screenshot from 2023-10-27 18-55-35

### Desktop

_No response_

### Mobile

_No response_

### Additional Context

_No response_

### LINKED ISSUE #5274: [BUG] ChakraUIInferencer code gen adding unneeded 'id'
### Describe the bug

Inferencer adding unneeded `.id` to useSelect defaultValue

### Steps To Reproduce

Use inferencer to generate Edit page

### Expected behavior

Default value to show in select component

### Screenshot

https://i.imgur.com/HFndV5j.png

With id
https://i.imgur.com/yMxh2pE.png

Without id
https://i.imgur.com/l2byTwd.png

### Desktop

Windows 11
Chrome
"@refinedev/core": "^4.28.2",
"@refinedev/chakra-ui": "^2.5.4",
Custom dataProvider

### Mobile

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aliemir**
- Show and List type inferencers were failing to provide a preview when there's a relational property without a presentational key. Updated generated code blocks to handle fields with no accessor keys and display a placeholder message instead.
- Even though `id` is required for Refine to work properly, in some list queries there may not be an `id` field. Material UI Datagrid requires an identifier for each row, if there's no `id` field, we're fallbacking to the first key of the row. Fixes the errors thrown for this case in Material UI List inferencers.
- Updated the object field inferencer to check for fields end with `name` and `label` and use them as the display name for the field. Previously the check was done for a predefined set of properties, now it's done for any property that ends with `name` or `label` which results with more accurate code generation.
- Fixed the issue of wrongfully assuming `id` key of relational fields in Chakra UI and Headless edit inferencers.
- 
### Closing issues

Fixes #5184
Fixes #5274

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

### CODE REVIEW

File: packages/inferencer/src/inferencers/antd/list.tsx [hunk 1]
```diff
@@ -152,21 +152,29 @@ export const renderer = ({
...
-                    val = valViewableSingle;
-                }
+                const cannotRender =
+                    field?.relationInfer &&
+                    field?.relationInfer?.type === "object" &&
+                    !field?.relationInfer?.accessor;
 
-                render = `render={(value: any[]) => ${loadingCondition} (
+                if (cannotRender) {
+                    render = `render={(value) => <span title="Inferencer failed to render this field (Cannot find key)">Cannot Render</span>}`;
```
Comment (BatuhanW) [inline packages/inferencer/src/inferencers/antd/list.tsx:161]:
```suggestion
                    render = `render={(value) => <span title="Inferencer failed to render this field: ${JSON.stringify(value)} (Cannot find key)">Cannot Render</span>}`;
```

Maybe we can mention value in the message for convenience.

File: packages/inferencer/src/inferencers/antd/show.tsx [hunk 2]
```diff
@@ -161,7 +162,7 @@ export const renderer = ({
                                 if (
                                     Array.isArray(field.relationInfer.accessor)
                                 ) {
-                                    return `Not Handled.`;
+                                    return `<span title="Inferencer failed to render this field. (Unsupported nesting)">Cannot Render</span>`;
                                     // return `{${multipleAccessor(
                                     //     `${variableName}?.data`,
                                     //     field.relationInfer.accessor,
```
Comment (BatuhanW) [inline packages/inferencer/src/inferencers/antd/show.tsx:168]:
```suggestion
```

**Review by BatuhanW — APPROVED** [review]
