### PR TITLE
fix: `<RefreshButton />` does not work

### LINKED ISSUE #4618: [BUG] RefreshButton does not refresh content
### Describe the bug

When using the default RefreshButton provider by <Show> component, the API is called and the new content is fetched. However, the content on UI remains the same and does not refresh.

### Steps To Reproduce

1. Created custom CRUD Rest API
2. Created basic refine project and use custom API as data provider
3. Click on "show" for any record
4. Change data in database or on API level
5. Click on "Refresh Button"
6. Check network or react-query logs, the new data is fetched but UI content is not updated

### Expected behavior

The UI data should be refreshed based on the latest data fetched from API

### Screenshot

_No response_

### Desktop

_No response_

### Mobile

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alicanerdurmaz**
`<RefreshButton />` was not functioning. This issue was resolved by using `useInvalidates` instead of `useOne`.

### Test plan (required)

- New tests are added.
- All tests are passed.

### Closing issues

closes #4618

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

### CODE REVIEW

File: packages/antd/src/components/buttons/refresh/index.tsx [hunk 1]
```diff
@@ -25,36 +28,45 @@ export const RefreshButton: React.FC<RefreshButtonProps> = ({
...
+
     return (
         <Button
-            // TODO: fix any type
-            onClick={(e) => (onClick ? onClick(e as any) : refetch())}
-            icon={<RedoOutlined spin={isFetching} />}
+            onClick={(e) => {
+                onClick?.(e);
+                handleInvalidate();
+            }}
```
Comment (salihozdemir) [inline packages/antd/src/components/buttons/refresh/index.tsx:68]:
```suggestion
            onClick={(e) => (onClick ? onClick(e) : refetch())}
```

This may be caused an issue, for users who previously passed `onClick`.

**Review by salihozdemir — CHANGES_REQUESTED** [review]

File: packages/ui-tests/src/tests/buttons/refresh.tsx [hunk 2]
```diff
@@ -4,7 +4,18 @@ import {
...
+import "@refinedev/core";
+
+const invalidateMock = jest.fn();
+jest.mock("@refinedev/core", () => ({
+    __esModule: true,
+    ...jest.requireActual("@refinedev/core"),
+    useInvalidate: () => {
+        return invalidateMock;
+    },
+}));
```
Comment (salihozdemir) [inline packages/ui-tests/src/tests/buttons/refresh.tsx:18]: Did not `jest.spyOn` work?

File: packages/chakra-ui/src/components/buttons/refresh/index.tsx [hunk 3]
```diff
@@ -14,51 +15,60 @@ import { IconRefresh } from "@tabler/icons";
...
  * `<RefreshButton>` uses Chakra UI {@link https://chakra-ui.com/docs/components/button `<Button> `} component.
- * to update the data shown on the page via the {@link https://refine.dev/docs/api-reference/core/hooks/data/useOne `useOne`} method provided by your dataProvider.
+ * to update the data shown on the page via the {@link https://refine.dev/docs/api-reference/core/hooks/invalidate/useInvalidate `useInvalidate`} hook.
  *
  * @see {@link https://refine.dev/docs/api-reference/chakra-ui/components/buttons/refresh-button} for more details.
  */
 export const RefreshButton: React.FC<RefreshButtonProps> = ({
     resource: resourceNameFromProps,
-    resourceNameOrRouteName,
+    resourceNameOrRouteName: propResourceNameOrRouteName,
```
Comment (salihozdemir) [inline packages/chakra-ui/src/components/buttons/refresh/index.tsx:28]: I think we should not rename prop name if is no conflict

File: packages/core/src/index.tsx [hunk 4]
```diff
@@ -117,6 +117,8 @@ export {
     matchResourceFromRoute,
     useActiveAuthProvider,
     useUserFriendlyName,
+    queryKeys,
+    pickDataProvider,
```
Comment (aliemir) [inline packages/core/src/index.tsx:121]: These exports doesn't have a corresponding changeset for the core package.

**Review by aliemir — CHANGES_REQUESTED** [review]
I think there's a missing changeset for `@refinedev/core`

File: examples/base-material-ui/package.json [hunk 5]
```diff
@@ -18,7 +18,8 @@
     "react-dom": "^18.0.0",
     "react-router-dom": "^6.8.1",
     "@uiw/react-md-editor": "^3.19.5",
-    "react-hook-form": "^7.30.0"
+    "react-hook-form": "^7.30.0",
+    "@tanstack/react-query-devtools": "^4.32.1"
```
Comment (aliemir) [inline examples/base-material-ui/package.json:22]: Let's remove this

**Review by aliemir — APPROVED** [review]

**Review by salihozdemir — APPROVED** [review]
