### PR TITLE
fix(inferencer): improve inferencer according to feedbacks

### LINKED ISSUE #3118: [BUG] using inferencer component with appwrite dataprovider
### Describe the bug

Using `inferencer` and `appwrite dataprovider` i got this `warning` message in the browser console, obviously the app doesn't work 
```
Formatting error in inferencer SyntaxError: An identifier or keyword cannot immediately follow a numeric literal. (3:26) (at bundle.js:267985:21)
  1 | import React from "react";import { useDataGrid, DataGrid, GridColumns, EditButton, ShowButton, DeleteButton, List, DateField } from "@pankod/refine-mui";
  2 |         
> 3 |         export const 6357a1b63ef8d80b30c6List = () => {
    |                          ^
  4 |             const { dataGridProps } = useDataGrid();
  5 |         
  6 |             
    at k (bundle.js:267985:21)
```

### Steps To Reproduce

configure resource name with appwrite collectionId e.g: 6357a1b12a5c0d9e41b2
```
function App() {
  return (
    <ThemeProvider theme={LightTheme}>
      <CssBaseline />
      <GlobalStyles styles={{ html: { WebkitFontSmoothing: "auto" } }} />
      <RefineSnackbarProvider>
        <Refine
          dataProvider={dataProvider(appwriteClient, {
            databaseId: "6357a1b12a5c0d9e41b2",  //moviedb
          })}
          liveProvider={liveProvider(appwriteClient, {
            databaseId: "6357a1b12a5c0d9e41b2",
          })}
          liveMode="auto"
          authProvider={authProvider}
          LoginPage={AuthPage}
          notificationProvider={notificationProvider}
          Layout={Layout}
          ReadyPage={ReadyPage}
          catchAll={<ErrorComponent />}
          routerProvider={routerProvider}
          resources={[
            {
              name: "6357a1b63ef8d80b30c6",
              list: MuiListInferencer,
              options: {
                label: 'Movies'
              }
            }
          ]}
        />
      </RefineSnackbarProvider>
    </ThemeProvider>
  );
}
```

### Expected behavior

that app works  :-)

### Screenshot

_No response_

### Desktop

_No response_

### Mobile

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by salihozdemir**
- Removed the requirement to define resource for relations.
- Component names and variable names are now generated primarily by label.
- Created base inferencer component.

### Test plan (required)

The tests are passed.

### Closing issues

closes #3118 

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

### CODE REVIEW

**Review by yildirayunlu — APPROVED** [review]

**Review by omeraplak — APPROVED** [review]

File: packages/inferencer/src/inferencers/antd/index.tsx [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+import { EditInferencer } from "./edit";
+import type { InferencerComponentProps } from "@/types";
+
+const AntdInferencer: React.FC<InferencerComponentProps> = ({
+    resource,
+    name,
+    action: actionFromProps,
+}) => {
+    const { useParams } = useRouterContext();
+    const { action } = useParams<ResourceRouterParams>();
```
Comment (omeraplak) [inline packages/inferencer/src/inferencers/antd/index.tsx:16]: Let's discuss this line

**Review by omeraplak — APPROVED** [review]

**Review by omeraplak — APPROVED** [review]

**Review by aliemir — APPROVED** [review]
