### PR TITLE
fix(appwrite): make `meta.permissions` overrideable

### LINKED ISSUE #5767: [BUG] Appwrite `dataProvider` meta.permissions (`@refinedev/appwrite`)
### Describe the bug

Hello,
how to override these default permissions in appwrite dataProvider? I don't want public permissions, only the permissions i set in meta at creation/edition.
```ts
  const { saveButtonProps, formProps, form } = useForm<HttpError>({
    meta: {
      readPermissions: [Permission.read(Role.user(identity.$id))],
      writePermissions: [Permission.write(Role.user(identity.$id))],
    },
  });
  ```
  
  I was able to walk-around it by making custom `dataProviderWrapper` that overrides the original `create` method
  ```ts
    return {
    ...originalDataProvider,
    create: async ({ resource, variables, meta }) => {
      const permissions = [
        // Permission.read(Role.any()),
        // Permission.write(Role.any()),
        ...(meta?.readPermissions ?? [Permission.read(Role.any())]),
        ...(meta?.writePermissions ?? [Permission.write(Role.any())]),
      ];
```

### Steps To Reproduce

1. create new app
```
npm create refine-app@latest -- --example data-provider-appwrite
```
2. use the following snippet with any roles.
```ts
  const { saveButtonProps, formProps, form } = useForm<HttpError>({
    meta: {
      readPermissions: [Permission.read(Role.user(identity.$id))],
      writePermissions: [Permission.read(Role.user(identity.$id))],
    },
  });
  ```

### Expected behavior

expected behavior is to be able to complete override the `meta` params.

### Packages

```json
    "@refinedev/antd": "^5.37.5",
    "@refinedev/appwrite": "^6.4.7",
    "@refinedev/core": "^4.48.0",
    "@refinedev/devtools": "^1.1.35",
    "@refinedev/kbar": "^1.3.7",
    "@refinedev/nextjs-router": "^6.0.1",
    "@refinedev/react-hook-form": "^4.8.15",
```

### Additional Context

sample after override

```ts
export const customDataProvider = (
  appwriteClient: Appwrite,
  options: { databaseId: string } = { databaseId: 'default' }
): Required<DataProvider> => {
  const { databaseId } = options;
  const database = new Databases(appwriteClient);
  const originalDataProvider: Required<DataProvider> = dataProvider(
    appwriteClient,
    {
      databaseId,
    }
  );

  return {
    ...originalDataProvider,
    create: async ({ resource, variables, meta }) => {
      const permissions = [
        // Permission.read(Role.any()),
        // Permission.write(Role.any()),
        ...(meta?.readPermissions ?? [Permission.read(Role.any())]), // new permisions
        ...(meta?.writePermissions ?? [Permission.write(Role.any())]), // new permisions
      ];

      const { $id, ...restData } = await database.createDocument(
        databaseId,
        resource,
        meta?.documentId ?? ID.unique(),
        variables as unknown as object,
        permissions
      );

      return {
        data: {
          id: $id,
          ...restData,
        },
      } as any;
    },
}
```

### PR DESCRIPTION
**Pull request by a-essawy**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

Users couldn't override the default `readPermissions` /  `writePermissions` values.

## What is the new behavior?

Users are able to override the default permissions by passing `options.defaultReadPermissions` / `options.defaultWritePermissions` OR by passing `meta?.readPermissions` / `meta?.writePermissions`.

If user passed `options.defaultReadPermissions` AND `meta?.readPermissions`, then the priority will be as following:

`meta?.readPermissions` if not? then `options.defaultReadPermissions` if not? then `Role.any()`.

fixes #5767 

## Notes for reviewers

This should be compatible with old users who are not passing `meta?.readPermissions` and expecting to get `Role.any()` by default.

### CODE REVIEW

**Review by aliemir — CHANGES_REQUESTED** [review]
Hey @abdelrahman-essawy thank you for the contribution! I think the `defaultReadPermissions` and `defaultWritePermissions`  should respect the previous values:

```ts
[
  Permission.read(Role.any()),
  Permission.write(Role.any()),
]
```

to avoid any breaking changes due to this PR.

Am I missing something here?

**Comment by abdelrahman-essawy** [comment]
Hey @aliemir , please check out my discussion https://github.com/refinedev/refine/issues/5767#issuecomment-2006964445 with @BatuhanW on this regard, and tell me what you think.

**Comment by aliemir** [comment]
> Hey @aliemir , please check out my discussion [#5767 (comment)](https://github.com/refinedev/refine/issues/5767#issuecomment-2006964445) with @BatuhanW on this regard, and tell me what you think.

Just discussed with @BatuhanW about this again. Here on [Default Values - Permissions docs of Appwrite](https://appwrite.io/docs/advanced/platform/permissions#default-values) says that if there's no explicit permissions, client SDK will provide permissions to the author.

Tested out with our `data-provider-appwrite` example and used two different accounts. I can confirm that I was unable to update the record created with another account when I don't pass explicit permissions. 

I confirm that this will be a breaking change if default permissions will be empty. Can you make the necessary changes to avoid this breaking change? 🙏 If you can, please let us know. We'll mark this PR to be included in our May release 🚀 

We'll review again after you make the changes 🙌

File: packages/appwrite/src/dataProvider.ts [hunk 1]
```diff
@@ -6,11 +6,25 @@ import {
...
-  options: { databaseId: string } = { databaseId: "default" },
+  options: DefaultOptions = {
+    databaseId: "default",
+    defaultReadPermissions: [],
+    defaultWritePermissions: [],
+  },
 ): Required<DataProvider> => {
-  const { databaseId } = options;
+  const {
+    databaseId,
```
Comment (aliemir) [inline packages/appwrite/src/dataProvider.ts:24]: Can we also add the `"default"` here to make sure we keep the default values correct?

File: packages/appwrite/src/dataProvider.ts [hunk 2]
```diff
@@ -6,11 +6,25 @@ import {
   getAppwriteSorting,
 } from "./utils";
 
+type DefaultOptions = {
+  databaseId: string;
+  defaultReadPermissions?: Permission[];
+  defaultWritePermissions?: Permission[];
```
Comment (aliemir) [inline packages/appwrite/src/dataProvider.ts:12]: Since we've added the ability to configure permissions through `dataProvider` instance. Can we add a section like "Handling Permissions" to our Appwrite docs? https://refine.dev/docs/data/packages/appwrite/#example Adding a small section above "Example" section will be enough I guess. 

Can you add this?

**Review by aliemir — CHANGES_REQUESTED** [review]
Thank you for the update @abdelrahman-essawy, just left two small comments. Hope you can have time to check those 🙏

**Comment by abdelrahman-essawy** [comment]
> Thank you for the update @abdelrahman-essawy, just left two small comments. Hope you can have time to check those 🙏

you are very welcome, sure thing!

File: .changeset/tasty-garlics-notice.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"@refinedev/appwrite": minor
+---
+
+fixing an issue which didn't allow users to override the default `readPermissions` / `writePermissions` values `Role.any()`, by passing `defaultReadPermissions` / `defaultWritePermissions` OR by passing `meta?.readPermissions` / `meta?.writePermissions`.
```
Comment (aliemir) [inline .changeset/tasty-garlics-notice.md:5]:
```suggestion
fix: add ability to customize default permission without explicitly passing them on each mutation

fixing an issue which didn't allow users to override the default `readPermissions` / `writePermissions` values `Role.any()`, by passing `defaultReadPermissions` / `defaultWritePermissions` OR by passing `meta?.readPermissions` / `meta?.writePermissions`.
```

**Review by aliemir — APPROVED** [review]
