### PR TITLE
fix(inferencer): update number field checks

### LINKED ISSUE #3550: [BUG] ChakraUIEditInferencer treats number fields as strings when edited
### Describe the bug

An example of the generated code is 

```ts
<FormControl mb="3" isInvalid={!!(errors as any)?.outstanding_amount}>
        <FormLabel>Outstanding Amount</FormLabel>
        <Input
          type="number"
          {...register("outstanding_amount", {
            required: "This field is required"
          })}
        />
        <FormErrorMessage>
          {(errors as any)?.outstanding_amount?.message as string}
        </FormErrorMessage>
      </FormControl>
```

The `<input>` type is correctly set to `number` but when the user edits the field the value sent to the server is actually of a `string` type. 

### Steps To Reproduce

Use ChakraUIEditInferencer to generate a UI

### Expected behavior

The generator should accommodate number types

This can be solved by adding `valueAsNumber: true` to the register options, like so 

```ts
      <FormControl mb="3" isInvalid={!!(errors as any)?.outstanding_amount}>
        <FormLabel>Outstanding Amount</FormLabel>
        <Input
          type="number"
          {...register("outstanding_amount", {
            required: "This field is required",
            valueAsNumber: true,
          })}
        />
        <FormErrorMessage>
          {(errors as any)?.outstanding_amount?.message as string}
        </FormErrorMessage>
      </FormControl>
```

### Screenshot

_No response_

### Desktop

_No response_

### Mobile

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aliemir**
Updated the number field checks for the inferencer, now string values will also be checked for numeric values.

### Closing issues

Resolves #3550

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

### CODE REVIEW

**Review by omeraplak — APPROVED** [review]

File: packages/inferencer/src/field-inferencers/number.ts [hunk 1]
```diff
@@ -1,9 +1,25 @@
...
+
+    console.log({
+        key,
+        value,
+        isNumeric,
+        isNumber,
+        isNumericString,
+        isNotNaN,
+        isNonEmptyString,
+    });
```
Comment (salihozdemir) [inline packages/inferencer/src/field-inferencers/number.ts:20]:
```suggestion
```
console hunter here! 😅

**Review by salihozdemir — APPROVED** [review]

**Review by alicanerdurmaz — APPROVED** [review]

File: packages/inferencer/src/field-inferencers/number.ts [hunk 2]
```diff
@@ -1,9 +1,16 @@
...
 export const numberInfer: FieldInferencer = (key, value) => {
+    const isNonEmptyString = typeof value === "string" && value.length > 0;
+    const isNotNaN = !isNaN(value as number);
+
+    const isNumericString = isNonEmptyString && isNotNaN;
     const isNumber = typeof value === "number";
 
-    if (isNumber) {
+    const isNumeric = isNumericString || isNumber;
+
```
Comment (aliemir) [inline packages/inferencer/src/field-inferencers/number.ts:11]:
```suggestion
```
